name: Build .NET 6 Project

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: 'Select the type of build'
        required: true
        default: 'all'  # You can change the default value

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build and Test
      run: |
        dotnet restore
        dotnet build
        dotnet test